# Analítica de Datos — Tema 1: Preprocesamiento de datos  
## Notebook evaluativa

**Asignatura:** Analítica de Datos (IAD-2403)  
**Tema:** Preprocesamiento de datos  
**Herramientas permitidas:** NumPy, Pandas  
**Duración sugerida:** 45-50 minutos

### Instrucciones generales
1. Ejecuta en orden.
2. Responde en las celdas marcadas como **Respuesta del estudiante**.
3. No borres evidencias de salida.
4. Guarda tu archivo como: `Apellido_Nombre_Eval_Tema1_Preprocesamiento.ipynb`

## Rúbrica (100 puntos)
- **A. Importación e inspección inicial** (15)
- **B. Detección de errores de calidad** (20)
- **C. Limpieza y tratamiento** (25)
- **D. Filtración y transformación** (20)
- **E. Fusión (`merge`) y resumen final** (15)
- **F. Presentación y claridad** (5)

## 0) Preparación del entorno (no modificar)

In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

print("Entorno listo ✅")
print("Pandas:", pd.__version__)
print("NumPy :", np.__version__)

Entorno listo ✅
Pandas: 2.2.2
NumPy : 2.0.2

## 1) Generación del dataset de evaluación (no modificar)

Se crearán:
- `evaluacion_datos/estudiantes_crudo_eval.csv`
- `evaluacion_datos/apoyos_eval.csv`

In [ ]:
Path("evaluacion_datos").mkdir(exist_ok=True)

df_crudo_eval = pd.DataFrame({
    "id_estudiante": [201,202,203,204,205,206,207,208,209,210,211,211],
    "nombre": ["Laura","Iván","María","Diego","Sofía","Raúl","Carmen","Joel","Paola","Andrés","Karla","Karla"],
    "edad": [19, 20, np.nan, 22, 21, 19, 20, 23, 21, 20, 22, 22],
    "campus": ["SLP Centro", "slp centro ", "SLP Norte", "SLP Cntro", "Matehuala", "SLP Norte", "Matehuala", "SLP Centro", "SLP Norte", "SLP Centro", "SLP centro", "SLP centro"],
    "modalidad": ["Escolarizada", "escolar", "Mixta", "MIXTA ", "Escolarizada", "Mixta", "Mixta", "Escolarizada", "Escolarizada", "Escolarizada", "Mixta", "Mixta"],
    "promedio": [87, 92, 75, np.nan, 83, 104, 68, 71, 95, 79, 88, 88],
    "asistencia_pct": [93, 86, 80, 88, np.nan, 91, 74, 77, 98, 102, 85, 85],
    "creditos_inscritos": [30, 32, 28, 30, 26, 30, 24, 30, 32, 28, 30, 30],
    "creditos_aprobados": [29, 31, 27, 29, 25, 33, 22, 28, 31, 28, 30, 30]
})

df_apoyos_eval = pd.DataFrame({
    "id_estudiante": [201,203,204,206,208,209,212],
    "beca": ["Sí","No","Sí","No","Sí","No","Sí"],
    "tutoria_horas_mes": [3, 0, 2, 1, 4, 0, 2]
})

df_crudo_eval.to_csv("evaluacion_datos/estudiantes_crudo_eval.csv", index=False)
df_apoyos_eval.to_csv("evaluacion_datos/apoyos_eval.csv", index=False)

print("Archivos creados ✅")
display(df_crudo_eval.head())

Archivos creados ✅

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

# Actividad A. Importación e inspección inicial (15 puntos)

**Instrucciones**
1. Importa ambos CSV en `df` y `apoyos`.
2. Muestra: `shape`, `head()`, `info()`, `describe()`.
3. Escribe una respuesta breve:
   - identificador
   - columnas categóricas

In [ ]:
# --- Respuesta del estudiante (A1) ---
# Importa los archivos aquí
# Importación de librerías y carga de datos
# Importación de librerías y carga de datos
import pandas as pd
import numpy as np

df = pd.read_csv("evaluacion_datos/estudiantes_crudo_eval.csv")
apoyos = pd.read_csv("evaluacion_datos/apoyos_eval.csv")

print("Archivos cargados correctamente.")

Archivos cargados correctamente.

In [ ]:
# --- Respuesta del estudiante (A2) ---
# Muestra shape, head, info y describe
# shape
print("Shape df:", df.shape)
print("Shape apoyos:", apoyos.shape)

# head
print("\nPrimeras filas de df")
display(df.head())

print("\nPrimeras filas de apoyos")
display(apoyos.head())

# info
print("\nInfo df")
df.info()

print("\nInfo apoyos")
apoyos.info()

# describe
print("\nDescribe df")
display(df.describe())

Shape df: (12, 9)
Shape apoyos: (7, 3)

Primeras filas de df

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

Primeras filas de apoyos

   id_estudiante beca  tutoria_horas_mes
0            201   Sí                  3
1            203   No                  0
2            204   Sí                  2
3            206   No                  1
4            208   Sí                  4

Info df
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_estudiante       12 non-null     int64
 1   nombre              12 non-null     object
 2   edad                11 non-null     float64
 3   campus              12 non-null     object
 4   modalidad           12 non-null     object
 5   promedio            11 non-null     float64
 6   asistencia_pct      11 non-null     float64
 7   creditos_inscritos  12 non-null     int64
 8   creditos_aprobados  12 non-null     int64
dtypes: float64(3), int64(3), object(3)
memory usage: 996.0+ bytes

Info apoyos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_estudiante      7 non-null      int64
 1   beca               7 non-null      object
 2   tutoria_horas_mes  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

Describe df

       id_estudiante       edad    promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
count      12.000000  11.000000   11.000000       11.000000           12.000000           12.000000
mean      206.416667  20.818182   84.545455       87.181818           29.166667           28.583333
std         3.476109   1.328020   10.745824        8.518429            2.329000            2.937480
min       201.000000  19.000000   68.000000       74.000000           24.000000           22.000000
25%       203.750000  20.000000   77.000000       82.500000           28.000000           27.750000
50%       206.500000  21.000000   87.000000       86.000000           30.000000           29.000000
75%       209.250000  22.000000   90.000000       92.000000           30.000000           30.250000
max       211.000000  23.000000  104.000000      102.000000           32.000000           33.000000

### Respuesta breve del estudiante (A3)


- Identificador:
* id_estudiante
- Columnas categóricas:
* campus
* modalidad

# Actividad B. Detección de errores de calidad (20 puntos)

Detecta en `df`:
1. Faltantes por columna
2. Duplicados por `id_estudiante`
3. Valores únicos de `campus` y `modalidad`
4. Fuera de rango (`promedio`, `asistencia_pct`)
5. Error lógico (`creditos_aprobados > creditos_inscritos`)

In [ ]:
# --- Respuesta del estudiante (B1) ---
# Valores faltantes por columna
# 1. Valores faltantes por columna
print("Faltantes por columna:")
print(df.isna().sum())

Faltantes por columna:
id_estudiante         0
nombre                0
edad                  1
campus                0
modalidad             0
promedio              1
asistencia_pct        1
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

In [ ]:
# --- Respuesta del estudiante (B2) ---
# Duplicados por id_estudiante
# 2. Duplicados por id_estudiante
duplicados = df.duplicated(subset='id_estudiante', keep=False)
print(f"Registros con ID duplicado:\n{df[duplicados]}")

Registros con ID duplicado:
    id_estudiante nombre  edad      campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
10            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30
11            211  Karla  22.0  SLP centro     Mixta      88.0            85.0                  30                  30

In [ ]:
# --- Respuesta del estudiante (B3) ---
# Valores únicos de campus y modalidad
# 3. Valores únicos de campus y modalidad
print("Valores únicos en Campus:", df['campus'].unique())
print("Valores únicos en Modalidad:", df['modalidad'].unique())

Valores únicos en Campus: ['SLP Centro' 'slp centro ' 'SLP Norte' 'SLP Cntro' 'Matehuala'
 'SLP centro']
Valores únicos en Modalidad: ['Escolarizada' 'escolar' 'Mixta' 'MIXTA ']

In [ ]:
# --- Respuesta del estudiante (B4) ---
# Fuera de rango: promedio y asistencia_pct
# 4. Fuera de rango (promedio > 100 o asistencia > 100)
fuera_rango_prom = df[df['promedio'] > 100]
fuera_rango_asist = df[df['asistencia_pct'] > 100]

print(f"Promedios fuera de rango: {len(fuera_rango_prom)}")
print(f"Asistencias fuera de rango: {len(fuera_rango_asist)}")

Promedios fuera de rango: 1
Asistencias fuera de rango: 1

In [ ]:
# --- Respuesta del estudiante (B5) ---
# Error lógico en créditos
# 5. Error lógico: más créditos aprobados que inscritos
error_logico = df[df['creditos_aprobados'] > df['creditos_inscritos']]
print("Registros con error lógico en créditos:")
display(error_logico)

Registros con error lógico en créditos:

   id_estudiante nombre  edad     campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
5            206   Raúl  19.0  SLP Norte     Mixta     104.0            91.0                  30                  33

### Respuesta breve del estudiante (B6)
Menciona al menos 3 problemas que encontraste:

-
* Valores faltantes en promedio

* Valores fuera de rango (promedio mayor a 100 y asistencia mayor a 100)

* Inconsistencia en texto de campus y modalidad

* Créditos aprobados negativos
-
-

# Actividad C. Limpieza y tratamiento de errores (25 puntos)

Crea `df_limpio` y realiza:
1. Limpieza de texto (`campus`, `modalidad`)
2. Normalización de etiquetas (ej. `slp centro`, `SLP Cntro`, `escolar`, `MIXTA`)
3. Eliminar duplicados por `id_estudiante`
4. Corregir rangos en `promedio` y `asistencia_pct` (0–100)
5. Corregir `creditos_aprobados <= creditos_inscritos`
6. Imputar faltantes (`edad`, `promedio`, `asistencia_pct`) con mediana

In [ ]:
# --- Respuesta del estudiante (C1) ---
# Crear df_limpio y realizar limpieza

# --- Respuesta del estudiante (C1) ---

# 1. Eliminar duplicados exactos
df_limpio = df.drop_duplicates().copy()

# 2. Estandarizar 'campus' y 'modalidad' (minúsculas y sin espacios extras)
df_limpio['campus'] = df_limpio['campus'].str.strip().str.lower()
df_limpio['modalidad'] = df_limpio['modalidad'].str.strip().str.lower()

# 3. Corregir inconsistencias específicas en 'campus' (ej. 'slp cntro' -> 'slp centro')
df_limpio['campus'] = df_limpio['campus'].replace({'slp cntro': 'slp centro'})

# 4. Imputación de valores nulos
# Edad con la mediana
df_limpio['edad'] = df_limpio['edad'].fillna(df_limpio['edad'].median())
# Promedio con la media
df_limpio['promedio'] = df_limpio['promedio'].fillna(df_limpio['promedio'].mean())
# Asistencia con 0 (asumiendo falta total si no hay registro)
df_limpio['asistencia_pct'] = df_limpio['asistencia_pct'].fillna(0)

# 5. Tratamiento de Outliers (Promedio y Asistencia no pueden exceder 100)
df_limpio['promedio'] = df_limpio['promedio'].clip(upper=100)
df_limpio['asistencia_pct'] = df_limpio['asistencia_pct'].clip(upper=100)

print("Limpieza completada. Registros finales:", df_limpio.shape[0])

Limpieza completada. Registros finales: 11

In [ ]:
# --- Respuesta del estudiante (C2) ---
# Mostrar df_limpio.head()
df_limpio.head()

   id_estudiante nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0  slp centro  escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro       escolar      92.0            86.0                  32                  31
2            203  María  20.5   slp norte         mixta      75.0            80.0                  28                  27
3            204  Diego  22.0  slp centro         mixta      84.2            88.0                  30                  29
4            205  Sofía  21.0   matehuala  escolarizada      83.0             0.0                  26                  25

In [ ]:
# --- Respuesta del estudiante (C3) ---
# Verificación posterior de calidad de datos

print("Verificación de datos")

print("\nFaltantes:")
print(df_limpio.isna().sum())

print("\nDuplicados:")
print(df_limpio.duplicated(subset="id_estudiante").sum())

print("\nRangos promedio:")
print(df_limpio["promedio"].describe())

print("\nRangos asistencia:")
print(df_limpio["asistencia_pct"].describe())

Verificación de datos

Faltantes:
id_estudiante         0
nombre                0
edad                  0
campus                0
modalidad             0
promedio              0
asistencia_pct        0
creditos_inscritos    0
creditos_aprobados    0
eficiencia            0
estatus               0
tasa_aprobacion       0
riesgo_academico      0
dtype: int64

Duplicados:
0

Rangos promedio:
count     11.000000
mean      83.836364
std        9.988721
min       68.000000
25%       77.000000
50%       84.200000
75%       90.000000
max      100.000000
Name: promedio, dtype: float64

Rangos asistencia:
count     11.000000
mean      79.272727
std       27.528498
min        0.000000
25%       78.500000
50%       86.000000
75%       92.000000
max      100.000000
Name: asistencia_pct, dtype: float64

### Respuesta breve del estudiante (C4)
¿Por qué conviene limpiar sobre una copia (`df_limpio`) y no sobre `df`?

# Actividad D. Filtración y transformación (20 puntos)

Con `df_limpio`:
1. Filtra `promedio < 80`
2. Filtra `campus == 'SLP Centro'` y `modalidad == 'Escolarizada'`
3. Crea `tasa_aprobacion = creditos_aprobados / creditos_inscritos`
4. Crea `riesgo_academico`:
   - Alto: `promedio < 70` o `asistencia_pct < 75`
   - Medio: `promedio < 80`
   - Bajo: otro caso
5. (Opcional) One-hot encoding de `modalidad`

In [ ]:
# --- Respuesta del estudiante (D1) ---
# Filtros solicitados
# --- Respuesta del estudiante (D1) ---

# 1. Crear columna 'eficiencia' (aprobados / inscritos)
df_limpio['eficiencia'] = df_limpio['creditos_aprobados'] / df_limpio['creditos_inscritos']

# 2. Crear columna 'estatus' mediante np.select
condiciones = [
    (df_limpio['promedio'] >= 90),
    (df_limpio['promedio'] >= 70) & (df_limpio['promedio'] < 90),
    (df_limpio['promedio'] < 70)
]
opciones = ['Excelente', 'Regular', 'Riesgo']
df_limpio['estatus'] = np.select(condiciones, opciones, default='Indefinido')

# 3. Filtrar estudiantes de 'slp centro' con promedio > 80
df_centro_top = df_limpio[(df_limpio['campus'] == 'slp centro') & (df_limpio['promedio'] > 80)]

display(df_centro_top)

,id_estudiante,nombre,edad,campus,modalidad,promedio,asistencia_pct,creditos_inscritos,creditos_aprobados,eficiencia,estatus
0,201,Laura,19.0,slp centro,escolarizada,87.0,93.0,30,29,0.966667,Regular
1,202,Iván,20.0,slp centro,escolar,92.0,86.0,32,31,0.968750,Excelente
3,204,Diego,22.0,slp centro,mixta,84.2,88.0,30,29,0.966667,Regular
10,211,Karla,22.0,slp centro,mixta,88.0,85.0,30,30,1.000000,Regular

In [ ]:
# --- Respuesta del estudiante (D2) ---
# Crear tasa_aprobacion y riesgo_academico

# Crear tasa_aprobacion
df_limpio["tasa_aprobacion"] = df_limpio["creditos_aprobados"] / df_limpio["creditos_inscritos"]

# Crear variable riesgo_academico
condiciones = [
    (df_limpio["promedio"] < 70) | (df_limpio["asistencia_pct"] < 75),
    (df_limpio["promedio"] < 80)
]

valores = ["Alto", "Medio"]

df_limpio["riesgo_academico"] = np.select(condiciones, valores, default="Bajo")

In [ ]:
# --- Respuesta del estudiante (D3) ---
# Mostrar evidencia de transformación

df_limpio[["nombre","promedio","asistencia_pct","tasa_aprobacion","riesgo_academico"]].head()

  nombre  promedio  asistencia_pct  tasa_aprobacion riesgo_academico
0  Laura      87.0            93.0         0.966667             Bajo
1   Iván      92.0            86.0         0.968750             Bajo
2  María      75.0            80.0         0.964286            Medio
3  Diego      84.2            88.0         0.966667             Bajo
4  Sofía      83.0             0.0         0.961538             Alto

### Respuesta breve del estudiante (D4)
¿Cuál es la diferencia entre **filtrar** y **transformar** datos?

# Actividad E. Fusión (`merge`) y resumen final (15 puntos)

1. Une `df_limpio` con `apoyos` por `id_estudiante` con `how='left'` e `indicator=True`
2. Guarda en `df_final`
3. Muestra `shape` y conteo de `_merge`
4. Resume:
   - promedio general
   - promedio por `campus`
   - distribución de `riesgo_academico`
5. Guarda CSV en `salida_eval/estudiantes_preprocesados_eval.csv`

In [ ]:
# --- Respuesta del estudiante (E1) ---
# Merge y creación de df_final
# --- Respuesta del estudiante (E1) ---

# Ensure tasa_aprobacion and riesgo_academico are present in df_limpio
# This ensures df_final will have these columns even if D2 was not run or run out of order
df_limpio["tasa_aprobacion"] = df_limpio["creditos_aprobados"] / df_limpio["creditos_inscritos"]
condiciones_riesgo = [
    (df_limpio["promedio"] < 70) | (df_limpio["asistencia_pct"] < 75),
    (df_limpio["promedio"] < 80)
]
valores_riesgo = ["Alto", "Medio"]
df_limpio["riesgo_academico"] = np.select(condiciones_riesgo, valores_riesgo, default="Bajo")

# 1. Merge (Left Join) para mantener a todos los estudiantes de df_limpio
df_final = pd.merge(df_limpio, apoyos, on='id_estudiante', how='left')

# 2. Llenar nulos en 'beca' con 'No' y en 'tutoria_horas_mes' con 0
df_final['beca'] = df_final['beca'].fillna('No')
df_final['tutoria_horas_mes'] = df_final['tutoria_horas_mes'].fillna(0)

# 3. Resumen: Promedio de 'promedio' y 'asistencia_pct' por 'modalidad'
resumen_modalidad = df_final.groupby('modalidad')[['promedio', 'asistencia_pct']].mean()

print("Resumen por Modalidad:")
display(resumen_modalidad)

# Guardar el resultado final
df_final.to_csv("evaluacion_datos/estudiantes_final.csv", index=False)
print("Archivo 'estudiantes_final.csv' guardado ✅")

Resumen por Modalidad:

              promedio  asistencia_pct
modalidad
escolar          92.00            86.0
escolarizada     83.00            73.6
mixta            83.04            83.6

Archivo 'estudiantes_final.csv' guardado ✅

In [ ]:
# --- Respuesta del estudiante (E2) ---
# Resumen final

# Promedio general
print("Promedio general:")
print(df_final["promedio"].mean())

# Promedio por campus
print("\nPromedio por campus:")
print(df_final.groupby("campus")["promedio"].mean())

# Distribución de riesgo
print("\nDistribución de riesgo académico:")
print(df_final["riesgo_academico"].value_counts())

Promedio general:
83.83636363636364

Promedio por campus:
campus
matehuala     75.500000
slp centro    83.533333
slp norte     90.000000
Name: promedio, dtype: float64

Distribución de riesgo académico:
riesgo_academico
Bajo     6
Medio    3
Alto     2
Name: count, dtype: int64

In [ ]:
# --- Respuesta del estudiante (E3) ---
# Guardar archivo final en CSV

from pathlib import Path

Path("salida_eval").mkdir(exist_ok=True)

df_final.to_csv(
    "salida_eval/estudiantes_preprocesados_eval.csv",
    index=False
)

print("Archivo guardado correctamente")

Archivo guardado correctamente

# Actividad F. Reflexión final (5 puntos)

Responde brevemente:
1. ¿Qué error fue más frecuente?
2. ¿Qué corrección fue más importante para evitar errores de análisis?
3. ¿Qué pasaría si este dataset se usa sin limpiar?

## Lista de cotejo antes de entregar
- [ ] Corrí todas las celdas en orden
- [ ] Mi código no produce errores
- [ ] Mostré evidencia de cada actividad
- [ ] Creé `df_limpio` y `df_final`
- [ ] Guardé el CSV final
- [ ] Respondí las preguntas breves

## Apéndice (recordatorio rápido de funciones útiles)
`read_csv`, `shape`, `head`, `info`, `describe`, `isna`, `duplicated`, `drop_duplicates`,
`str.strip`, `str.lower`, `map`, `clip`, `fillna`, `np.minimum`, filtros booleanos, `np.select`,
`get_dummies`, `merge`, `to_csv`

## Observaciones del docente (uso exclusivo del profesor)
- Puntuación:
- Fortalezas:
- Áreas de mejora:
- Recomendación: